site_name: JsonifyCraft
site_description: JsonifyCraft is a content creation mod that allows defining your own custom items, blocks, and more with JSON!
site_author: Timothy Metcalfe
copyright: ©Timothy Metcalfe 2020
theme: readthedocs
extra_css:
- css/extra.css
nav:
  - JsonifyCraft: 'index.md'
  - Discord: 'https://discord.gg/Ca2hx6X'
  - Game Objects:
    - 'items.md'
    - 'blocks.md'
    - 'food.md'
  - Bits:
    - 'bits/effectdescription.md'
    - 'bits/harvester.md'
  - Registries:
    - 'registries/mapcolor.md'
    - 'registries/material.md'
    - 'registries/rarity.md'
    - 'registries/soundtype.md'
    - 'registries/tabgroup.md'
    - 'registries/tooltype.md'
  - Examples:
    - 'examples/dirt.md'
    - 'examples/tallgrass.md'
